spring.application.name=controle-estoque

# Configura o drive e a url do db, deixando como um arquivo fixo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./controle-estoque

# Usuário e senha no banco
spring.datasource.username=sa
spring.datasource.password=

# Permite que acesse o banco pela url localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Associa as Entities as suas tabelas
spring.jpa.hibernate.ddl-auto=update